import type { Metadata } from "next";
import "@fortawesome/fontawesome-free/css/all.min.css";
import "bootstrap/dist/css/bootstrap.min.css";
import BootstrapClient from "./BootstrapClient";
import "./globals.css";
import "swiper/css";


import "../assets/css/style.css";
import "../assets/css/webslidemenu.css";
import "../assets/css/footer.css";
import "../assets/css/new-style.css";
import "../assets/css/caseStudy-inner.css";
import "../assets/css/fade-down.css";
import Navbar from "@/components/client/Navcontainer";
import { Poppins } from "next/font/google";
import Providers from "@/redux/Provider";
import Footer from "@/components/server/Footer";
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">

      <Providers>
        <Navbar />
        <BootstrapClient />
        {children}
        <Footer />
      </Providers>

    </html>
  );
}
